import { relations, sql } from "drizzle-orm";
import { pgTable, varchar, uuid, timestamp } from "drizzle-orm/pg-core";

import { users } from "./users.js";

/**
 * Sessions table for Lucia v3 authentication.
 *
 * Lucia manages session lifecycle:
 * - Session IDs are cryptographically random 40-character strings
 * - Sessions have configurable expiration (default 30 days)
 * - Fresh sessions (< 50% lifetime remaining) are automatically extended
 * - Expired sessions are validated as null and should be deleted
 *
 * @see https://lucia-auth.com/database/
 */
export const sessions = pgTable("sessions", {
  /**
   * Session ID - generated by Lucia, 40-character random string.
   * This is the value stored in the session cookie.
   */
  id: varchar("id", { length: 255 }).primaryKey(),

  /**
   * User ID foreign key with CASCADE delete.
   * When a user is deleted, all their sessions are automatically removed.
   */
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id, { onDelete: "cascade" }),

  /**
   * Session expiration timestamp.
   * Lucia checks this during validation - expired sessions return null.
   */
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),

  /**
   * Session context - personal, shared, or unknown.
   * Used to determine session duration and security policies.
   */
  context: varchar("context", { length: 20 }).notNull().default("unknown"),

  /**
   * Last activity timestamp for idle timeout detection.
   * Updated on each request to track session activity.
   * Note: Using sql`now()` instead of .defaultNow() for consistent Drizzle push behavior.
   */
  lastActivityAt: timestamp("last_activity_at", { withTimezone: true })
    .notNull()
    .default(sql`now()`),
});

/**
 * Relations for Drizzle query builder.
 * Enables: db.query.sessions.findFirst({ with: { user: true } })
 */
export const sessionsRelations = relations(sessions, ({ one }) => ({
  user: one(users, {
    fields: [sessions.userId],
    references: [users.id],
  }),
}));

/**
 * Session type for select operations (reading from database).
 */
export type Session = typeof sessions.$inferSelect;

/**
 * NewSession type for insert operations (writing to database).
 */
export type NewSession = typeof sessions.$inferInsert;

// Add metadata accessor for test compatibility
Object.defineProperty(sessions, "_", {
  get() {
    return {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment -- Required for test metadata accessor
      name: Symbol.for("drizzle:Name") in sessions
        // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-member-access -- Required for test metadata accessor
        ? (sessions as any)[Symbol.for("drizzle:Name")]
        : "sessions",
    };
  },
  enumerable: false,
  configurable: true,
});
